---
- name: Install turnserver packge
  yum: name={{item}} state=latest
  with_items: install.packages

- name: Ensure directory exists
  file: path={{ item }} state=directory owner=easemob group=easemob
  with_items:
    - /data/apps/config/turnserver/
    - /data/apps/data/turnserver/
    - /data/apps/log/turnserver/
    - /data/apps/opt/turnserver/bin/
    - /data/apps/var/turnserver/
    - /etc/turnserver/


- name: chown /data/apps/  for easemob
  command: chown -R easemob:easemob /data/apps/


- name: Put on the media conf files
  template: src={{item.src}} dest={{item.dest}} owner=easemob group=easemob mode={{item.mode}} backup=yes
  with_items:
  - { src: 'turnserver.conf', dest: '/etc/turnserver/turnserver.conf', mode: 644 }
  - { src: 'monit/turnserver.mc', dest: '/data/apps/config/monit/turnserver.mc', mode: 750 }
  - { src: 'shutdown.sh', dest: '/data/apps/opt/turnserver/bin/shutdown.sh', mode: 750 }




- name: restart monit
  service: name=monit state=restarted

- name: restart ejabberd
  monit: name=ejabberd state=restarted


