- name: Remove easemob-rest packge
  yum: name=easemob-rest state=absent

- name: Install easemob-rest packge
  yum: name={{item}} state=installed
  with_items: profile.packages

- name: Put on the easemob-rest conf files
  template: src={{item.src}} dest={{item.dest}} owner=easemob group=easemob mode={{item.mode}} force=yes
  with_items:
  - { src: 'data/apps/config/easemob-rest/server-start.sh', dest: '/data/apps/config/easemob-rest/server-start.sh', mode: 755 }
  - { src: 'data/apps/config/easemob-rest/server-stop.sh', dest: '/data/apps/config/easemob-rest/server-stop.sh', mode: 755 }
  - { src: 'data/apps/config/monit/easemob-rest.mc', dest: '/data/apps/config/monit/easemob-rest.mc', mode: 644 }
  notify:
  - restart easemob-rest
  tags:
    - update_rest_config

- name: reload monit
  command: monit reload
  tags:
    - reload_monit
