---

depend_packages:
  - epel-release
  - java-1.8.0-openjdk
  - java-1.8.0-openjdk-devel
  - unzip
  - tar

zookeeper_packages:
  - name: zookeeper
    version: 3.4.11
    url: "https://download.pingcap.org/zookeeper-3.4.11.tar.gz"
    checksum: "sha256:f6bd68a1c8f7c13ea4c2c99f13082d0d71ac464ffaf3bf7a365879ab6ad10e84"

zk_data_dir: "{{ deploy_dir }}/data"
zk_datalog_dir: "{{ deploy_dir }}/datalog"
zk_log_dir: "{{ deploy_dir }}/log"
zk_run_dir: "{{ deploy_dir }}/scripts"
zk_link_dir: "{{ deploy_dir }}/zk"
zk_java_env: "{{ zk_link_dir }}/conf/java.env"
zk_maxClientCnxns: "60"
zk_heap_size: "2G"
