---
- name: Install ejabberd packge
  yum: name={{item}} state=latest
  with_items: ejabberd_install.packages

- name: Create the symbol link of the ejabberd dir
  file: src=/data/apps/opt/ejabberd dest=/opt/ejabberd state=link

- name: Create the ejabberd direcotries
  file: path={{item}} owner=easemob group=easemob state=directory recurse=yes
  with_items:
  - /data/apps/var/ejabberd
    
- name: Put on the ejabberd conf files
  template: src={{item.src}} dest={{item.dest}} owner=easemob group=easemob mode={{item.mode}}
  with_items:
  - { src: 'data/apps/opt/ejabberd/etc/ejabberd/ejabberdctl.cfg', dest: '/data/apps/opt/ejabberd/etc/ejabberd/ejabberdctl.cfg', mode: 644 }
  - { src: 'data/apps/opt/ejabberd/etc/ejabberd/inetrc', dest: '/data/apps/opt/ejabberd/etc/ejabberd/inetrc', mode: 644 }
  - { src: 'data/apps/opt/ejabberd/etc/ejabberd/ejabberd.yml', dest: '/data/apps/opt/ejabberd/etc/ejabberd/ejabberd.yml', mode: 644 }
  - { src: 'data/apps/opt/ejabberd/var/lib/ejabberd/.erlang.cookie', dest: '/data/apps/opt/ejabberd/var/lib/ejabberd/.erlang.cookie', mode: 400 }
  - { src: 'data/apps/config/monit/ejabberd.mc', dest: '/data/apps/config/monit/ejabberd.mc', mode: 750 }
  - { src: 'data/apps/opt/ejabberd/etc/ejabberd/ebs.pem', dest: '/data/apps/opt/ejabberd/etc/ejabberd/ebs.pem', mode: 644 }
  notify:
  - reload monit
