---
- name: Install easemob-redis package
  yum: name={{item}} state=latest 
  with_items: redis.packages

- name: Put on the redis conf files
  template: src={{item.src}} dest={{item.dest}} owner=easemob group=easemob mode={{item.mode}}
  with_items:
  - { src: 'data/apps/config/redis/redis.conf', dest: '/data/apps/config/redis/redis.conf', mode: 644 }
  - { src: 'data/apps/config/monit/redis.mc', dest: '/data/apps/config/monit/redis.mc', mode: 644 }
  notify:
    - reload monit
    - restart redis

- name: Put on the redis slave conf files
  template: src={{item.src}} dest={{item.dest}} owner=easemob group=easemob mode={{item.mode}}
  with_items:
  - { src: 'data/apps/config/redis/redis-slave.conf', dest: '/data/apps/config/redis/redis-slave.conf', mode: 644 }
  - { src: 'data/apps/config/monit/redis-slave.mc', dest: '/data/apps/config/monit/redis-slave.mc', mode: 644 }
  when: is_redis_slave == "True"
  notify:
    - reload monit
    - restart redis-slave
    - reload monit
