#usergrid_propertise
redis1_master: "127.0.0.1"
redis1_slave: "127.0.0.1"
redis2_master: "127.0.0.1"
redis2_slave: "127.0.0.1"
redis_rest_message: "127.0.0.1"
redis_ejabberd_message: "127.0.0.1"
redis_chatgroup: "127.0.0.1"

cassandra_url: 127.0.0.1
cassandra_seeds: 127.0.0.1:9160

ejabberd_host: "127.0.0.1"
ejabberd_domain: "easemob.com"

kafka_broker_list: 127.0.0.1:9092

zookeeper_url: 127.0.0.1:2181

sysadmin:
  name: webmaster
  password: ssy123WEBmaster
  email: webmaster@easemob.com
  is_first_login: false
  is_admin_confirm: true

usergrid_url:
  api_site: ""
  console_site: ""
