- include_vars: ../../inventory/ssy/inventory-list.yml

- name: Add the host into inventory
  add_host: name={{item.name}} groups={{item.group}} ip={{item.ip}} hostname={{item.name}}
  with_items: inventory.hosts

- name: Put the file /etc/hosts
  template: src=etc/hosts dest=/etc/hosts owner=root group=root mode=644



