---
#source init_dev.sh
- hosts: all
#  connection: local
  remote_user: ec2-user
  gather_facts: True
  become: yes
  tasks:
    - name: create-arvon
      user:
        name: arvon
    - name: add ssh path
      file:
        path: /home/arvon/.ssh/
        state: directory
        mode: 0755
    - name: add auth file
      file:
        path: /home/arvon/.ssh/authorized_keys
        owner: arvon
        group: arvon
        state: touch
        mode: 0644
    - name: add ssh-key to hosts
      lineinfile:
        destfile : /home/arvon/.ssh/authorized_keys
        line: 'ssh-rsa xxxxxxxx'
