- name: Create groups
  group: name={{item.group}}  state=present
  with_items: users

- name: Create the users
  user: name={{ item.user }} 
        state=present 
        password={{ item.passwd }} 
        shell={{ item.shell }} 
        comment="{{ item.comment }}"
        group={{ item.group }}         
  with_items: users

- name: Auth | Make sure the users can do sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^{{ item.user }}' line='{{ item.user }} ALL=(ALL) NOPASSWD: ALL'" 
  with_items: users

- name: Auth | Make tty can do sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^Defaults    requiretty' line='#Defaults    requiretty'"
  with_items: users

