- name: check supervisor install or not
  shell: command -v supervisord
  register: result
  ignore_errors: True

- name: copy start config to supervisor config dir
  template: src=supervisor_etcd.conf.j2 dest=/etc/supervisord/conf.d/etcd.conf mode=0644
  when: result.stdout is defined

- name : restart supervisor
  service:  name=supervisor state=restarted

- name: start supervisor etcd
  supervisorctl:
    name: etcd
    state: started
