---
- name: Install media packge
  yum: name={{item}} state=latest
  with_items: install.packages

#- name: Create the symbol link of the ejabberd dir
#  file: src=/data/apps/opt/media dest=/opt/media state=link


- name: Put on the media conf files
  template: src={{item.src}} dest={{item.dest}} owner=easemob group=easemob mode={{item.mode}} backup=yes
  with_items:
  - { src: 'mserver.ini', dest: '/data/apps/config/mediaserver/mserver.ini', mode: 644 }
  - { src: 'monit/media-server.mc', dest: '/data/apps/config/monit/media-server.mc', mode: 750 }


#- name: Create the dir /opt/shell
#  file: path=/opt/shell state=directory owner=easemob group=easemob

#- name: Put on the log script and set the cron job
#  copy: src=ejabberd_error.sh dest=/opt/shell/ejabberd_error.sh owner=easemob group=easemob mode=755

- name: Ensure directory exists
  file: path={{ item }} state=directory owner=easemob group=easemob
  with_items:
    - /data/apps/config/mediaserver/
    - /data/apps/data/mediaserver/
    - /data/apps/log/mediaserver/
    - /data/apps/opt/mediaserver/
    - /data/apps/var/mediaserver/

- name: chown /data/apps/  for easemob
  command: chown -R easemob:easemob /data/apps/

- name: update sysctl.conf 
  lineinfile: dest=/etc/sysctl.conf regexp='^net.core.wmem_max =' line='net.core.wmem_max = 104857600'
  lineinfile: dest=/etc/sysctl.conf regexp='^net.core.rmem_max =' line='net.core.rmem_max = 104857600'

- name: reload sysctl
  command: /sbin/sysctl -p
  ignore_errors: yes

- name: restart monit
  service: name=monit state=restarted

- name: restart ejabberd
  monit: name=ejabberd state=restarted


