---
- name: Install easemob web packages
  yum: name={{item}} state=latest 
  with_items: web_install.packages

- name: Put on the nginx conf files
  template: src={{ item.src }} dest={{ item.dest }} owner=easemob group=easemob mode={{ item.mode }}
  with_items:
    - { src: data/apps/config/nginx/conf.d/api.conf, dest: /data/apps/config/nginx/conf.d/api.conf, mode: 640 }  
    - { src: data/apps/config/nginx/conf.d/console.conf, dest: /data/apps/config/nginx/conf.d/console.conf, mode: 640 } 
    - { src: data/apps/config/nginx/conf.d/webim.conf, dest: /data/apps/config/nginx/conf.d/webim.conf, mode: 640 }
    - { src: data/apps/config/nginx/conf.d/im-api.conf, dest: /data/apps/config/nginx/conf.d/im-api.conf, mode: 640 }
    - { src: data/apps/config/nginx/conf.d/tcp/sdk-api.conf, dest: /data/apps/config/nginx/conf.d/tcp/sdk-api.conf, mode: 640 }
  notify:
  - reload monit
  - reload monit
  - reload nginx

- name: Put on the webim and console files
  template: src={{ item.src }} dest={{ item.dest }} owner=easemob group=easemob mode={{ item.mode }}
  with_items:
    - { src: data/apps/data/nginx/webim/static/js/easemob.im.config.js, dest: /data/apps/data/nginx/webim/static/js/easemob.im.config.js, mode: 644 }  
